name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Kext
        run: |
          PROJECT_PATH=$(find . -name "*.xcodeproj" -print -quit)
          xcodebuild -project "$PROJECT_PATH" -target RTL8821CEwifi -configuration Release -sdk macosx
      - name: Upload Kext
        uses: actions/upload-artifact@v4
        with:
          name: RTL8821CEwifi-Kext
          path: build/Release/RTL8821CEwifi.kext
