name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Kext
        run: |
          # 1. Move into the folder where the project lives
          cd RTL8821CE
          
          # 2. Build the project using the local file
          xcodebuild -project RTL8821CEwifi.xcodeproj -configuration Release -sdk macosx
          
      - name: Upload Kext
        uses: actions/upload-artifact@v4
        with:
          name: RTL8821CEwifi-Kext
          path: RTL8821CE/build/Release/*.kext
