name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Wipe and Fresh Clone
        run: |
          # This ignores your current repo and gets the real code
          git clone --recursive https://github.com/crangel660/RTL8821CEwifi.kext.git fresh_source
          
      - name: Build Kext
        run: |
          cd fresh_source
          # We check the internal folder where the .xcodeproj actually lives
          cd RTL8821CE
          xcodebuild -project RTL8821CEwifi.xcodeproj -target RTL8821CEwifi -configuration Release -sdk macosx
          
      - name: Upload Kext
        uses: actions/upload-artifact@v4
        with:
          name: RTL8821CEwifi-Kext
          path: fresh_source/RTL8821CE/build/Release/*.kext
