name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Driver
        run: make
      - name: Upload Kext
        uses: actions/upload-artifact@v4
        with:
          name: RTL8821CEwifi-Kext
          path: ./*.kext
