name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Force Clone Source
        run: |
          git clone --recursive https://github.com/crangel660/RTL8821CEwifi.kext.git source
          
      - name: Build Kext
        run: |
          cd source
          # Find any .xcodeproj file and save its location
          PROJECT_FILE=$(find . -name "*.xcodeproj" -print -quit)
          echo "Found project at: $PROJECT_FILE"
          
          # Build using the found project file
          xcodebuild -project "$PROJECT_FILE" -configuration Release -sdk macosx
          
      - name: Upload Kext
        uses: actions/upload-artifact@v4
        with:
          name: RTL8821CEwifi-Kext
          path: source/**/build/Release/*.kext
